title: Tales of the Holy Mysticat
email: publisher@banotpress.com
description: >- # this means to ignore newlines until "baseurl:"
  Jewish Wisdom Stories by a Feline Mystic, as collected by Rachel Adler, published by Banot Press.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mysticattales.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  markfullmer

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
